# ==============================================================================
# USER CONFIGURATION: plugins.conf
# ==============================================================================
# Add your custom settings for plugins here.
# These will override or add to the defaults found in ~/.config/hypr/source/plugins.conf
# ==============================================================================

plugin {
    hyprbars {
        # example config
        bar_height = 20
        # bar_color = $primary
        bar_color = rgba(28333f90)
        bar_bur = true

        bar_title_enabled = true
        bar_text_size = 10
        bar_text_font = JetBrains Mono Nerd Font

        bar_text_align = center
        bar_buttons_alignment = left

        col.text = $shadow

        bar_padding = 8
        bar_button_padding = 8

        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(ff4040), 10, 󰖭, hyprctl dispatch killactive
        # hyprbars-button = rgb(eeee11), 10, , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(eeee11), 10, , hyprctl dispatch fullscreen 1

        # cmd to run on double click of the bar
        on_double_click = hyprctl dispatch fullscreen 1
    }
}